version: '3'

services:
  angular:
    container_name: angular
    build: storage
    ports:
      - "4200:80"
  express:
    container_name: express
    build: backend
    ports:
      - "4000:4000"
    links:
      - database
  database:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"